Added configurable API_URL
tomaskazatel/baserow-client pull request #5
Opened 2023-07-17 16:41 UTC by levinside

This usecase is for self-hosted instances.

2023-07-17 19:03 UTC, tomaskazatel requested changes
Thank you so much for your code to develop this package. The code looks very good, could you please add new parametr to the README.md specifically this section https://github.com/tomaskazatel/baserow-client#creating-a-baserow-instance?

2023-07-17 19:03 UTC, tomaskazatel commented on Baserow.ts
> +    apiKey = 'https://api.baserow.io',
You have typo here. There should be `apiUrl = ...`

2023-07-18 22:25 UTC, levinside commented
> ...could you please add new parametr to the README.md

I'm not so good in english. Please take a look.

2023-07-19 07:08 UTC, tomaskazatel commented on README.md
> +To use the Baserow SDK Client, you need to create a `Baserow` instance by providing your API key. Optionally, you can specify whether to show user field names.
Maybe a little tweak

```suggestion
To use the Baserow SDK Client, you need to create a `Baserow` instance by providing your API key. Optionally, you can specify whether to show user field names or custom url for self host instances.  
```

2023-07-19 07:09 UTC, tomaskazatel commented on README.md
> +To use the Baserow SDK Client, you need to create a `Baserow` instance by providing your API key. Optionally, you can specify whether to show user field names.
It looks awesome, little tweak.

2023-07-19 08:23 UTC, levinside commented on README.md
> +To use the Baserow SDK Client, you need to create a `Baserow` instance by providing your API key. Optionally, you can specify whether to show user field names.
Looks good.

2023-07-19 08:32 UTC, tomaskazatel approved these changes

2023-07-19 08:32 UTC, merged

2024-06-08 22:05 UTC, DiegoVenancioVieira commented
What about apiUrl dosen't exist? 
packson.json = "baserow-client": "^0.3.0",
![image](https://github.com/tomaskazatel/baserow-client/assets/27169911/01544a81-ec99-4962-8930-02b7334ca805)